dataset:
  train:  # LMDB
    type: PCB_dataset


    hr_train: ./dataset/DeepPCB/40_e2e/train/HQ
    lr_train: ./dataset/DeepPCB/40_e2e/train/LQ
    label_train: ./dataset/DeepPCB/40_e2e/train/labels

    hr_val: ./dataset/DeepPCB/40_e2e/val/HQ
    lr_val: ./dataset/DeepPCB/40_e2e/val/LQ
    label_val: ./dataset/DeepPCB/40_e2e/val/labels

    meta_info_fp: log/log.txt

    imgsz: 160 # ground truth patch size: gt_size * gt_size
    augment: True
    scale: 4

    # for datasampler
    enlarge_ratio: 300  # enlarge dataset by randomly cropping.

    # for dataloader   Defined in utils/deep_learning.py
    num_worker_per_gpu: 8  # 12 in total. mainly affect IO
    batch_size_per_gpu: 2  # bs=8, divided by 1 GPUs

comet_logging:
  using: False
  previous_experiment: False
  api_key: mkfmxVIjacb8h74qKO6NzPdPN # your comet api key
  project_name: compressed-deeppcb
  workspace: dangdinh17

AMP: True

network:
  iqe_type: Enhancer_Small
  isr_type: ESR
  detection: YOLOv8
  machine_type: machine  # box / class / machine
  loss_type: human   # machine / human / total
  train_type: srqe  # sr or srqe or qesr or qe
  loss_balance: default    # dwa / uncertainty_weight / gradnorm / default 

exp: exp_deeppcb

train:
  num_gpu: 1
  exp_name: SRQE_DEEP_Human_QF40 # default: timestr. None: ~
  random_seed: 7
  num_iter: 100000
  interval_train:  1
  load_path: None
  load_detection: None
  best_iqe_model: None
  best_isr_model: None
  best_detection_model: exp_deeppcb/weights/deep_yolov8n.pt
  w_h: 1
  w_m: 0.01
  num_classes: 6
  name_classes:
    1: mousebite
    2: open
    3: pin-hole
    4: short
    5: spur
  optim:
    type: Adam
    lr: !!float 1e-4  #  #  1e-4  5e-5  # init lr of scheduler
    betas: [0.9, 0.999]
    eps: !!float 1e-07

  scheduler:
    is_on: True
    type: CosineAnnealingRestartLR
    periods: [!!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4]  # epoch interval
    restart_weights: [1, 0.5, 0.5, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  detection_scheduler:
      periods: [!!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4]  # epoch interval
      restart_weights: [1, 0.5, 0.5, 0.5, 0.5, 0.5]
      eta_min: !!float 1e-5

  detection_optim:
    type: SGD
    lr: !!float 0.0005  #  #  1e-4  5e-5  # init lr of scheduler
    momentum: 0.937
    nesterov: True
    weight_decay: 5e-4

  loss:  # Defined in utils/deep_learning.py
    #type: CharbonnierLoss
    eps: !!float 1e-6
    type: CharbonnierLoss


  criterion: # Defined in utils/deep_learning.py
    type: PSNR
    unit: dB

